In [40]:
import pandas as pd
import numpy as np

In [57]:
d_f = pd.read_csv('LoanX.csv')

In [58]:
d_f.head()

Unnamed: 0   Loan_ID Gender Married Dependents     Education Self_Employed  \
0           0  LP001002   Male      No          0      Graduate            No   
1           1  LP001003   Male     Yes          1      Graduate            No   
2           2  LP001005   Male     Yes          0      Graduate           Yes   
3           3  LP001006   Male     Yes          0  Not Graduate            No   
4           4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [59]:
d_f.describe()

Unnamed: 0  ApplicantIncome  CoapplicantIncome  LoanAmount  \
count  614.000000       614.000000         614.000000  614.000000   
mean   306.500000      5403.459283        1621.245798  146.412162   
std    177.390811      6109.041673        2926.248369   84.037468   
min      0.000000       150.000000           0.000000    9.000000   
25%    153.250000      2877.500000           0.000000  100.250000   
50%    306.500000      3812.500000        1188.500000  129.000000   
75%    459.750000      5795.000000        2297.250000  164.750000   
max    613.000000     81000.000000       41667.000000  700.000000   

       Loan_Amount_Term  Credit_History  
count        614.000000      614.000000  
mean         342.410423        0.855049  
std           64.428629        0.352339  
min           12.000000        0.000000  
25%          360.000000        1.000000  
50%          360.000000        1.000000  
75%          360.000000        1.000000  
max          480.000000        1.000000

In [60]:
d_f.columns

Index(['Unnamed: 0', 'Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [74]:
import scipy.stats as stats
import seaborn as sns
from sklearn.feature_selection import chi2
from scipy.stats import chi2_contingency
from scipy.stats import norm
from scipy.stats import chi2

In [75]:
df_table = pd.crosstab(d_f['Property_Area'], d_f['Loan_Status'])
print(df_table)

Loan_Status     N    Y
Property_Area         
Rural          69  110
Semiurban      54  179
Urban          69  133


In [76]:
observed_values = df_table.values
print("Observed Values:- \n", observed_values)

Observed Values:- 
 [[ 69 110]
 [ 54 179]
 [ 69 133]]


In [77]:
val = chi2_contingency(df_table)
val

(12.297623130485675,
 0.0021360187811644937,
 2,
 array([[ 55.97394137, 123.02605863],
        [ 72.85993485, 160.14006515],
        [ 63.16612378, 138.83387622]]))

In [78]:
Expected_Values=val[3]
Expected_Values

array([[ 55.97394137, 123.02605863],
       [ 72.85993485, 160.14006515],
       [ 63.16612378, 138.83387622]])

In [79]:
no_of_rows = len(df_table.iloc[0:3,0])
no_of_cols = len(df_table.iloc[0,0:2])
ddof = (no_of_rows - 1)*(no_of_cols - 1)
print("Degree of Freedom:- ", dof)
alpha =0.05

Degree of Freedom:-  2


In [80]:
chi_square = sum([o-e ** 2./e for o,e in zip(observed_values, Expected_values)])
chi_square_statstic = chi_square[0] + chi_square[1]
print("chi_square_statstic: ", chi_square_statstic)

chi_square_statstic:  585.4004817014663


In [81]:
critical_value=chi2.ppf(q=1-alpha , df=ddof)
print('critical_value:',critical_value)

critical_value: 5.991464547107979


In [83]:
p_value = 1 - chi2.cdf(x = chi_square_statstic , df = ddof)
print("P-value: ", p_value)
print("Significance level: ", alpha)
print("Degree Of Freedom: ",ddof)

P-value:  0.0
Significance level:  0.05
Degree Of Freedom:  2


In [116]:
df_table = pd.crosstab(d_f['Loan_Status'], d_f['Dependents'])
print(df_table)

Dependents     0   1   2  3+
Loan_Status                 
N            113  36  25  18
Y            247  66  76  33


In [117]:
observed_values2 = df_table.values
print("Observed Values2:- \n", observed_values2)

Observed Values2:- 
 [[113  36  25  18]
 [247  66  76  33]]


In [118]:
val2 = chi2_contingency(df_table)
val2

(3.1513990012324227,
 0.3688663081366005,
 3,
 array([[112.5732899 ,  31.89576547,  31.58306189,  15.94788274],
        [247.4267101 ,  70.10423453,  69.41693811,  35.05211726]]))

In [119]:
Expected_Values_2=val2[3]
Expected_Values_2

array([[112.5732899 ,  31.89576547,  31.58306189,  15.94788274],
       [247.4267101 ,  70.10423453,  69.41693811,  35.05211726]])

In [120]:
no_of_rows = len(df_table.iloc[0:2,0])
no_of_cols = len(df_table.iloc[0,0:4])
ddof = (no_of_rows - 1)*(no_of_cols - 1)
print("Degree of Freedom:- ", ddof)
alpha =0.05

Degree of Freedom:-  3


In [121]:
chi_square2 = sum([o-e ** 2./e for o,e in zip(observed_values2, Expected_Values_2)])
chi_square_statstic2 = chi_square2[0] + chi_square2[1]
print("chi_square_statstic2: ", chi_square_statstic2)

chi_square_statstic2:  0.0


In [122]:
critical_value2=chi2.ppf(q=1-alpha , df=ddof)
print('critical_value2:',critical_value2)

critical_value2: 7.814727903251179


In [140]:
d_f.describe().transpose()

count         mean          std    min      25%     50%  \
Unnamed: 0         614.0   306.500000   177.390811    0.0   153.25   306.5   
ApplicantIncome    614.0  5403.459283  6109.041673  150.0  2877.50  3812.5   
CoapplicantIncome  614.0  1621.245798  2926.248369    0.0     0.00  1188.5   
LoanAmount         614.0   146.412162    84.037468    9.0   100.25   129.0   
Loan_Amount_Term   614.0   342.410423    64.428629   12.0   360.00   360.0   
Credit_History     614.0     0.855049     0.352339    0.0     1.00     1.0   

                       75%      max  
Unnamed: 0          459.75    613.0  
ApplicantIncome    5795.00  81000.0  
CoapplicantIncome  2297.25  41667.0  
LoanAmount          164.75    700.0  
Loan_Amount_Term    360.00    480.0  
Credit_History        1.00      1.0

In [149]:
yes=d_f[d_f['Credit_History'] == 1.0]
no=d_f[d_f['Credit_History'] == 0.0]

In [150]:
yes.shape

(525, 14)

In [152]:
no.shape

(89, 14)

In [153]:
s1 = yes.LoanAmount.var()
n1 = yes.LoanAmount.count()-1
s2 = no.LoanAmount.var()
n2 = no.LoanAmount.count()-1

print('s1: ',round(s1,3),'\ts2: ',round(s2,3))
print('n1: ',round(n1,3),'\tn2: ',round(n2,3))

s1:  7099.09 	s2:  6923.359
n1:  524 	n2:  88


In [240]:
F = s1/s2
F

1.0253823063974707

In [243]:
import scipy.stats
FTableStat=scipy.stats.f.ppf(q=1-.05, dfn=n1, dfd=n2)
FTableStat

1.3285544206680004

In [244]:
if(abs(F)<FTableStat):
    print("Accepting Null Hypothesis")
else:
    print("Accepting Alternate Hypothesis")

Accepting Null Hypothesis


In [130]:
yes=d_f[d_f['Loan_Status'] == 'Y']
no=d_f[d_f['Loan_Status'] == 'N']

In [131]:
x1 = yes.ApplicantIncome.mean()
s1 = yes.ApplicantIncome.std()
n1 = yes.ApplicantIncome.count()

x2 = no.ApplicantIncome.mean()
s2 = no.ApplicantIncome.std()
n2 = no.ApplicantIncome.count()

dof = n1+n2-2
#one tail test
#level of significance will be 95%

print('x1: ',round(x1,3),'\tx2: ',round(x2,3))
print('s1: ',round(s1,3),'\ts2: ',round(s2,3))
print('n1: ',round(n1,3),'\tn2: ',round(n2,3))
print('degree of freedom: ',dof)

x1:  5384.069 	x2:  5446.078
s1:  5765.442 	s2:  6819.559
n1:  422 	n2:  192
degree of freedom:  612


#Here we have sample statistics so we will apply t-test

$t_{test} = \frac{(x_1-x_2)}{\sqrt{(s_1^2/n_1^2+s_2^2/n_2^2)}}$

In [134]:
t = (x1-x2)/np.sqrt(((s1**2)/n1)+((s2**2)/n2))
print('t_test:', abs(round(t,3)))

t_test: 0.109


In [139]:
from scipy import stats
crtical = stats.t.ppf(1-0.05,df=dof)
crticalt

1.647347241930401

1.647347241930401


So our calculated value is greater than table value

$\therefore we \ will \ reject \ null \ hypothesis \ in \ favour \ of \ alternate \ hypothesis$

In [189]:
d_f['Loan_Status']=d_f['Loan_Status'].replace("N",0)

In [190]:
d_f['Loan_Status']

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [162]:
(d_f.corr() >=0.6).sum()

Unnamed: 0           1
ApplicantIncome      1
CoapplicantIncome    1
LoanAmount           1
Loan_Amount_Term     1
Credit_History       1
dtype: int64

In [191]:
d_f.columns

Index(['Unnamed: 0', 'Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [197]:
d_f_logit=pd.get_dummies(d_f,columns=['Gender','Married','Dependents','Education','Self_Employed','Property_Area'])

In [198]:
d_f_logit

Unnamed: 0   Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0             0  LP001002             5849                0.0  146.412162   
1             1  LP001003             4583             1508.0  128.000000   
2             2  LP001005             3000                0.0   66.000000   
3             3  LP001006             2583             2358.0  120.000000   
4             4  LP001008             6000                0.0  141.000000   
..          ...       ...              ...                ...         ...   
609         609  LP002978             2900                0.0   71.000000   
610         610  LP002979             4106                0.0   40.000000   
611         611  LP002983             8072              240.0  253.000000   
612         612  LP002984             7583                0.0  187.000000   
613         613  LP002990             4583                0.0  133.000000   

     Loan_Amount_Term  Credit_History  Loan_Status  Gender_Female  \
0               360.0             1.0            1              0   
1               360.0             1.0            0              0   
2               360.0             1.0            1              0   
3               360.0             1.0            1              0   
4               360.0             1.0            1              0   
..                ...             ...          ...            ...   
609             360.0             1.0            1              1   
610             180.0             1.0            1              0   
611             360.0             1.0            1              0   
612             360.0             1.0            1              0   
613             360.0             0.0            0              1   

     Gender_Male  ...  Dependents_1  Dependents_2  Dependents_3+  \
0              1  ...             0             0              0   
1              1  ...             1             0              0   
2              1  ...             0             0              0   
3              1  ...             0             0              0   
4              1  ...             0             0              0   
..           ...  ...           ...           ...            ...   
609            0  ...             0             0              0   
610            1  ...             0             0              1   
611            1  ...             1             0              0   
612            1  ...             0             1              0   
613            0  ...             0             0              0   

     Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                     1                       0                 1   
1                     1                       0                 1   
2                     1                       0                 0   
3                     0                       1                 1   
4                     1                       0                 1   
..                  ...                     ...               ...   
609                   1                       0                 1   
610                   1                       0                 1   
611                   1                       0                 1   
612                   1                       0                 1   
613                   1                       0                 0   

     Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                    0                    0                        0   
1                    0                    1                        0   
2                    1                    0                        0   
3                    0                    0                        0   
4                    0                    0                        0   
..                 ...                  ...                      ...   
609                  0                    1                        0   
610                  0       

In [193]:
d_f_logit

Unnamed: 0   Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0             0  LP001002             5849                0.0  146.412162   
1             1  LP001003             4583             1508.0  128.000000   
2             2  LP001005             3000                0.0   66.000000   
3             3  LP001006             2583             2358.0  120.000000   
4             4  LP001008             6000                0.0  141.000000   
..          ...       ...              ...                ...         ...   
609         609  LP002978             2900                0.0   71.000000   
610         610  LP002979             4106                0.0   40.000000   
611         611  LP002983             8072              240.0  253.000000   
612         612  LP002984             7583                0.0  187.000000   
613         613  LP002990             4583                0.0  133.000000   

     Loan_Amount_Term  Credit_History  Loan_Status  Gender_Female  \
0               360.0             1.0            1              0   
1               360.0             1.0            0              0   
2               360.0             1.0            1              0   
3               360.0             1.0            1              0   
4               360.0             1.0            1              0   
..                ...             ...          ...            ...   
609             360.0             1.0            1              1   
610             180.0             1.0            1              0   
611             360.0             1.0            1              0   
612             360.0             1.0            1              0   
613             360.0             0.0            0              1   

     Gender_Male  ...  Dependents_1  Dependents_2  Dependents_3+  \
0              1  ...             0             0              0   
1              1  ...             1             0              0   
2              1  ...             0             0              0   
3              1  ...             0             0              0   
4              1  ...             0             0              0   
..           ...  ...           ...           ...            ...   
609            0  ...             0             0              0   
610            1  ...             0             0              1   
611            1  ...             1             0              0   
612            1  ...             0             1              0   
613            0  ...             0             0              0   

     Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                     1                       0                 1   
1                     1                       0                 1   
2                     1                       0                 0   
3                     0                       1                 1   
4                     1                       0                 1   
..                  ...                     ...               ...   
609                   1                       0                 1   
610                   1                       0                 1   
611                   1                       0                 1   
612                   1                       0                 1   
613                   1                       0                 0   

     Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                    0                    0                        0   
1                    0                    1                        0   
2                    1                    0                        0   
3                    0                    0                        0   
4                    0                    0                        0   
..                 ...                  ...                      ...   
609                  0                    1                        0   
610                  0       

In [201]:
d_f_logit.columns

Index(['Unnamed: 0', 'Loan_ID', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Loan_Status',
       'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes',
       'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+',
       'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No',
       'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban',
       'Property_Area_Urban'],
      dtype='object')

In [212]:
X=d_f_logit[['Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes',
       'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+',
       'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No',
       'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban',
       'Property_Area_Urban', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History']]

In [203]:
X

Gender_Female  Gender_Male  Married_No  Married_Yes  Dependents_0  \
0                0            1           1            0             1   
1                0            1           0            1             0   
2                0            1           0            1             1   
3                0            1           0            1             1   
4                0            1           1            0             1   
..             ...          ...         ...          ...           ...   
609              1            0           1            0             1   
610              0            1           0            1             0   
611              0            1           0            1             0   
612              0            1           0            1             0   
613              1            0           1            0             1   

     Dependents_1  Dependents_2  Dependents_3+  Education_Graduate  \
0               0             0              0                   1   
1               1             0              0                   1   
2               0             0              0                   1   
3               0             0              0                   0   
4               0             0              0                   1   
..            ...           ...            ...                 ...   
609             0             0              0                   1   
610             0             0              1                   1   
611             1             0              0                   1   
612             0             1              0                   1   
613             0             0              0                   1   

     Education_Not Graduate  Self_Employed_No  Self_Employed_Yes  \
0                         0                 1                  0   
1                         0                 1                  0   
2                         0                 0                  1   
3                         1                 1                  0   
4                         0                 1                  0   
..                      ...               ...                ...   
609                       0                 1                  0   
610                       0                 1                  0   
611                       0                 1                  0   
612                       0                 1                  0   
613                       0                 0                  1   

     Property_Area_Rural  Property_Area_Semiurban  Property_Area_Urban  \
0                      0                        0                    1   
1                      1                        0                    0   
2                      0                        0                    1   
3                      0                        0                    1   
4                      0                        0                    1   
..                   ...                      ...                  ...   
609                    1                        0                    0   
610                    1                        0                    0   
611                    0                        0                    1   
612                    0                        0                    1   
613                    0                        1                    0   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000       

In [211]:
y=d_f_logit['Loan_Status']

In [208]:
y.value_counts()

1    422
0    192
Name: Loan_Status, dtype: int64

In [215]:
X.shape

(614, 20)

In [220]:
!pip install imblearn

In [221]:
from imblearn.over_sampling import SMOTE

In [223]:
from sklearn.model_selection import train_test_split

In [231]:
d_f_logit=d_f_logit.iloc[:,2:]

In [233]:
X = d_f_logit.loc[:, d_f_logit.columns != 'Loan_Status']
y = d_f_logit.loc[:, d_f_logit.columns == 'Loan_Status']
from imblearn.over_sampling import SMOTE
os = SMOTE(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
columns = X_train.columns
os_data_X,os_data_y=os.fit_resample(X_train, y_train)
os_data_X = pd.DataFrame(data=os_data_X,columns=columns )
os_data_y= pd.DataFrame(data=os_data_y,columns=['Loan_Status'])
# we can Check the numbers of our data
print("length of oversampled data is ",len(os_data_X))
print("Number of no subscription in oversampled data",len(os_data_y[os_data_y['Loan_Status']==0]))
print("Number of subscription",len(os_data_y[os_data_y['Loan_Status']==1]))
print("Proportion of no subscription data in oversampled data is ",len(os_data_y[os_data_y['Loan_Status']==0])/len(os_data_X))
print("Proportion of subscription data in oversampled data is ",len(os_data_y[os_data_y['Loan_Status']==1])/len(os_data_X))

length of oversampled data is  576
Number of no subscription in oversampled data 288
Number of subscription 288
Proportion of no subscription data in oversampled data is  0.5
Proportion of subscription data in oversampled data is  0.5


In [234]:
data_final_vars=d_f_logit.columns.values.tolist()
y=['Loan_Status']
X=[i for i in d_f_logit if i not in y]
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
rfe = RFE(logreg, 20)
rfe = rfe.fit(os_data_X, os_data_y.values.ravel())
print(rfe.support_)
print(rfe.ranking_)


[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


C:\Users\wajah\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=20 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [236]:
y

['Loan_Status']

In [239]:
import statsmodels.api as sm
logit_model=sm.Logit(d_f_logit[y],d_f_logit[X])
result=logit_model.fit()
print(result.summary2())

         Current function value: 0.453765
         Iterations: 35
                                     Results: Logit
Model:                      Logit                    Pseudo R-squared:         0.270     
Dependent Variable:         Loan_Status              AIC:                      587.2237  
Date:                       2021-09-08 16:36         BIC:                      653.5236  
No. Observations:           614                      Log-Likelihood:           -278.61   
Df Model:                   14                       LL-Null:                  -381.45   
Df Residuals:               599                      LLR p-value:              3.8125e-36
Converged:                  0.0000                   Scale:                    1.0000    
No. Iterations:             35.0000                                                      
-----------------------------------------------------------------------------------------
                         Coef.     Std.Err.      z    P>|z|      [0.025 

C:\Users\wajah\anaconda3\lib\site-packages\statsmodels\base\model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
